# Generated by Django 2.1.5 on 2019-02-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistic', '0002_readdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readdetail',
            name='readnum_ptr',
        ),
        migrations.DeleteModel(
            name='ReadDetail',
        ),
    ]
