# Generated by Django 2.1.5 on 2019-02-19 06:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistic', '0004_readdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='read_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 19, 6, 20, 3, 167113, tzinfo=utc)),
        ),
    ]
