# Generated by Django 2.1.7 on 2019-10-27 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('user', '0002_logincaptcha'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginError',
            fields=[
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_err_time', models.FloatField()),
                ('err_login_times', models.IntegerField()),
                ('block_state', models.BooleanField(default=False)),
            ],
        ),
    ]
